/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mstr_Produk;

import Class.logic_koneksi;
import Class.mstr_produk;
import java.awt.Dimension;
import java.awt.MenuContainer;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
//import lib dari java untuk gipanggil didalam prosedur eksekus


public final class _Entry extends javax.swing.JDialog {

    public static Connection getKoneksi() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form _Entry
     * @param parent
     * @param modal
     */
    
    public _Entry(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Dimension parentSize = this.getSize();
        this.setLocation((parentSize.width) / 2, (parentSize.height) / 2);
        this.setLocationRelativeTo(null);
        this.setAlwaysOnTop(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namaField = new javax.swing.JTextField();
        umurField = new javax.swing.JTextField();
        nohpField = new javax.swing.JTextField();
        b_simpan = new javax.swing.JButton();
        b_Keluar = new javax.swing.JButton();
        idpengunjungField = new javax.swing.JTextField();
        alamatField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Id pengunjung");

        jLabel2.setText("Nama");

        jLabel3.setText("alamat");

        jLabel4.setText("umur");

        jLabel5.setText("no HP");

        umurField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                umurFieldKeyTyped(evt);
            }
        });

        b_simpan.setText("Simpan");
        b_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_simpanActionPerformed(evt);
            }
        });

        b_Keluar.setText("Keluar");
        b_Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_KeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(b_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(b_Keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nohpField, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idpengunjungField, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alamatField, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(umurField, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idpengunjungField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alamatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(umurField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nohpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_simpan)
                    .addComponent(b_Keluar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_simpanActionPerformed
        // TODO add your handling code here:
        simpan();
    }//GEN-LAST:event_b_simpanActionPerformed

    private void b_KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_KeluarActionPerformed
        // TODO add your handling code here:
        keluar();
    }//GEN-LAST:event_b_KeluarActionPerformed

    private void namaFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaFieldKeyTyped
       char c = evt.getKeyChar();
       if (!((Character.isLetter(c)
             ||  (c == KeyEvent.VK_BACK_SPACE)
             ||  (c == KeyEvent.VK_DELETE)
             ||  (c == KeyEvent.VK_SPACE)
             ||  (c == KeyEvent.VK_ENTER)))) {
           getToolkit().beep();
           JOptionPane.showInternalMessageDialog(null, "Masukkan Huruf A-Z");
           evt.consume();
       }
       if (c == evt.VK_ENTER) {
           alamatField.requestFocus();
       }
        // TODO add your handling code here:
        
    }//GEN-LAST:event_namaFieldKeyTyped

    private void umurFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_umurFieldKeyTyped
        char c = evt.getKeyChar();
        if (!((Character.isDigit(c)
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE)
                || (c == KeyEvent.VK_ENTER)))) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Masukan angka 0-9");
            evt.consume();
        }
        if (c == evt.VK_ENTER) {
            b_simpan.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_umurFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc="//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(_Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(_Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(_Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(_Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                _Entry dialog = new _Entry(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatField;
    public javax.swing.JButton b_Keluar;
    public javax.swing.JButton b_simpan;
    private javax.swing.JTextField idpengunjungField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField namaField;
    private javax.swing.JTextField nohpField;
    private javax.swing.JTextField umurField;
    // End of variables declaration//GEN-END:variables

 
    
  private boolean append;
String Vprd_id, Vnama, Valamat, Vumur, VNo_HP;
String _temp_produk;
String _Status;
String _User;
//membuat dekarasi variabel
mstr_produk PD = new mstr_produk();
//membuat objek baru PD mewarisi class mstr_produk

//tambahan method
public _Entry() {
}

void autono () {
    try { 
        Connection _Cnn = logic_koneksi.getConnection();
        String sql = "select max(right(prd_id,5)) AS IdAuto from mstr_produk";
        Statement st = _Cnn.createStatement();
        ResultSet rs = st.executeQuery(sql);
        while (rs.next()) {
            if (rs.first() == false) {
                idpengunjungField.setText("P01");
            } else {
              rs.last();
              int auto_f = rs.getInt(1) + 1;
              String no = String.valueOf(auto_f);
              int NoLong = no.length();
              for (int a = 0; a < 6 - NoLong; a++) {
                  no = "0" + no;
              }
              idpengunjungField.setText("P0" + no);
            }
        }
        rs.close();
        st.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "ERROR: \n" + e.toString(), "Kesalahan", JOptionPane.WARNING_MESSAGE);
    }
}

void clearField() {
    idpengunjungField.setEditable(false);
    namaField.setEditable(false);
    alamatField.setEditable(false);
    umurField.setEditable(false);
    nohpField.setEditable(false);
    b_simpan.setVisible(append);
}
private boolean ValidasiInput() {
    boolean result = false;
    JOptionPane pane = new JOptionPane();
    
    if (idpengunjungField.getText().equals("")
            || namaField.getText().equals("")
            || alamatField.getText().equals("")
            || umurField.getText().equals("")
            || nohpField.getText().equals("")) {
        JDialog dialog = pane.createDialog(null,"Lengkapi Record Data");
        dialog.setAlwaysOnTop(true);
        dialog.setVisible(true);
        JOptionPane.showMessageDialog(this, "Atribut tidak valid", "Informasi", 0);//Awalnya Komentar
        if ((idpengunjungField.getText().equals(""))) {
           idpengunjungField.requestFocus();
           String id = JOptionPane.showInputDialog("Berapa id produk?");
           idpengunjungField.setText(id);
        }
        if ((namaField.getText().equals(""))) {
            namaField.requestFocus();
            String nama = JOptionPane.showInputDialog("Nama Produk?");
            namaField.setText(nama);
        }
        if ((alamatField.getText().equals(""))) {
            alamatField.requestFocus();
            String alamat = JOptionPane.showInputDialog("alamat?");
            alamatField.setText(alamat);
        }
        if ((umurField.getText().equals(""))) {
            umurField.requestFocus();
            String tp = JOptionPane.showInputDialog("umur?");
            umurField.setText(tp);
        }
        if ((nohpField.getText().equals(""))) {
            nohpField.requestFocus();
            String tp = JOptionPane.showInputDialog("No_HP?");
            nohpField.setText(tp);
        }
        result = false;
} else {
        result = true;
    }
    return result;
}
void simpan() {
    if (ValidasiInput() == false) {
        return;
    }else {
        try {
            PD.Cari(idpengunjungField.getText());
            PD.prd_id = idpengunjungField.getText();
            PD.nama = namaField.getText();
            PD.alamat = alamatField.getText();
            PD.umur = umurField.getText();
            PD.No_HP = nohpField.getText();
            if (PD._Akses.equals("-")) {
                idpengunjungField.setEditable(false);
                int pilih = JOptionPane.showConfirmDialog(this, "Record data : \n"
                        + idpengunjungField.getText() + "\n"
                        + namaField.getText() + "\n"
                        + alamatField.getText() + "\n"
                        + umurField.getText() + "\n"
                        + nohpField.getText() + "\n"
                        + "Akan terupdate ??", "NOTOFIKASI UPDATE RECORD", JOptionPane.YES_OPTION);
            if (pilih == JOptionPane.YES_OPTION) {
                PD.updatedata();
                clearField();
            }
        } else {
                idpengunjungField.setEditable(false);
                int pilih = JOptionPane.showConfirmDialog(this, "Record data : \n"
                        + idpengunjungField.getText() + "\n"
                        + namaField.getText() + "\n"
                        + alamatField.getText() + "\n"
                        + umurField.getText() + "\n"
                        + nohpField.getText() + "\n"
                        + "Akan ditambahkan ke databse PRODUK??", "NOTOFIKASI SIMPAN RECORD", JOptionPane.YES_OPTION);
                if (pilih == JOptionPane.YES_OPTION) {
                PD.simpandata();
                clearField();
            }
        }   
     } catch (Exception e) {
          JOptionPane.showMessageDialog(null, "Kesalahan " + e);    
        }
    }
}
        void keluar() {
            append = false;
            this.setVisible(append);
        }
        
        private void cari () {
            try {
                PD.Cari(_temp_produk);
                if (PD._Akses.equals("_")) {
                    idpengunjungField.setText(PD.prd_id);
                    namaField.setText(PD.nama);
                    alamatField.setText(PD.alamat);
                    umurField.setText(PD.umur);
                    nohpField.setText(PD.No_HP);
                    idpengunjungField.setEditable(false);
                }
            } catch (Exception e) {
                
            }
        }
        
        public _Entry(String user, String V_id_pd, String status)   {
            initComponents();
            autono();
            _temp_produk = V_id_pd;
            if (status.equals("Edit")) {
                System.out.println("kode dipilih " + V_id_pd);
                b_simpan.setText("Update");
            }
            _Status = status;
            _User = user;
            cari();       
    }
}