/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package report;

import Class.logic_koneksi;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import java.io.File;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JRViewer;

/**
 *
 * @author irsan
 */
public class FrmLaporanUser extends javax.swing.JInternalFrame {
    
    Timer stopwatch;
    int count = 0;
    int delay = 100;
    int countpassed = 1;
    private String _fileName;
    private HashMap _parameter;
    private net.sf.jasperreports.swing.JRViewer pracetak;
    private int countPassed;
    
    /**
     * Creates new form FrmLaporanUser
     */
    public FrmLaporanUser() {
        initComponents();
    }

     public void refresh() {
        try {
            ActionListener acl = new ActionListener() {
                public void actionPerformed (ActionEvent e) {
                    if (count == 0) {
                        stopwatch.stop();
                        detikLabel.setText("");
                    } else {
                        detikLabel.setText("Telah selesai " + count + " &");
                        count--;
                        count = jProgressBar1.getValue() + 20;
                        if (count > jProgressBar1.getMaximum()) {
                            count = jProgressBar1.getMinimum();
                        }
                        jProgressBar1.setValue(count);
                    }
                }
            };
            stopwatch = new Timer(delay, acl);
            stopwatch.setInitialDelay(0);
            stopwatch.start();
            count = countPassed;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR" + e);
        }
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        btampil = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        detikLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        btampil.setText("Tampilkan");
        btampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btampilActionPerformed(evt);
            }
        });

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        detikLabel.setText("detik");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btampil)
                .addGap(83, 83, 83)
                .addComponent(detikLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(keluar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btampil)
                    .addComponent(keluar)
                    .addComponent(detikLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btampilActionPerformed
        Cetak();
    }//GEN-LAST:event_btampilActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        this.hide();
    }//GEN-LAST:event_keluarActionPerformed

    private void FrmLaporanUser(String fileName) {
	logic_koneksi _cnn= new logic_koneksi();
	_cnn.makeConnect();
	_fileName = fileName;
	try{ 
		_fileName = _cnn.almDir + _fileName;
		_parameter = new HashMap();
		File lp = new File (_fileName);
		JasperReport jr = (JasperReport) JRLoader.loadObject(lp);
		JasperPrint jp = JasperFillManager.fillReport(jr, null, logic_koneksi.getConnection());
		pracetak = new net.sf.jasperreports.swing.JRViewer(jp);
		pracetak.setOpaque(true);
		pracetak.setVisible (true);
		setVisible(true);
		System.out.println("TERPANGGIL");
		jScrollPane1.add(pracetak);
		jScrollPane1.setViewportView(pracetak);
		this.setLocation(0, 0);
		this.setMaximum(true);
		} catch (Exception ex) {
			System.out.print(ex);
		}
	}

    private void Cetak() {
	refresh();
	try {
		if (btampil.getText().equals("Cetak Data User") == true) {
		FrmLaporanUser("lap_user.jasper");
		/* } else if (btampil.getText().equals("AAAA") == true){
		FrmLaporanUser("AAA.jasper");
		 } else if (btampil.getText().equals("AAAA") == true){
		FrmLaporanUser("AAA.jasper");
		 } else if (btampil.getText().equals("AAAA") == true){
		FrmLaporanUser("AAA.jasper");
		*/

		} else {
		JOptionPane.showMessageDialog(null, "Tidak Dapat_" + btampil.getText());
		btampil.
		setText("Tampilkan");
	}
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR" + e);
	}
    }


public static void main (String args[]) {


	java.awt.EventQueue.invokeLater(new Runnable() {
		public void run() {
			new FrmLaporanUser().setVisible(true);
		}
	});
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btampil;
    private javax.swing.JLabel detikLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    // End of variables declaration//GEN-END:variables
}
