/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mstr_User;

/**
 *
 * @author Glora Pratama
 */
import Class.logic_koneksi;
import Class.mstr_user;
import java.awt.Dimension;
import java.awt.MenuContainer;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

public class _Entry extends javax.swing.JDialog {

    /**
     * Creates new form _Entry
     */
    public _Entry(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Dimension parentSize = this.getSize();
        this.setLocation((parentSize.width) / 2, (parentSize.height) / 2);
        this.setLocationRelativeTo(null);
        this.setAlwaysOnTop(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        idDonaturLabel = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        alamatLabel = new javax.swing.JLabel();
        noTelpLabel = new javax.swing.JLabel();
        user_idField = new javax.swing.JTextField();
        namaField = new javax.swing.JTextField();
        tempat_lahirField = new javax.swing.JTextField();
        alamatField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        b_Keluar = new javax.swing.JButton();
        b_Simpan = new javax.swing.JButton();
        noTelpLabel1 = new javax.swing.JLabel();
        noTelpLabel2 = new javax.swing.JLabel();
        noTelpLabel3 = new javax.swing.JLabel();
        tanggal_lahirField = new javax.swing.JFormattedTextField();
        jenis_kelaminCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        idDonaturLabel.setText("User ID");

        namaLabel.setText("Nama");

        alamatLabel.setText("Jenis Kelamin");

        noTelpLabel.setText("Tempat Lahir");

        namaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                namaFieldKeyTyped(evt);
            }
        });

        b_Keluar.setText("Keluar");
        b_Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_KeluarActionPerformed(evt);
            }
        });

        b_Simpan.setText("Simpan");
        b_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_SimpanActionPerformed(evt);
            }
        });

        noTelpLabel1.setText("Tanggal Lahir");

        noTelpLabel2.setText("Alamat");

        noTelpLabel3.setText("Password");

        tanggal_lahirField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-M-d"))));

        jenis_kelaminCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis Kelamin", "Laki-laki", "Perempuan" }));
        jenis_kelaminCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenis_kelaminComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(idDonaturLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(user_idField, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namaLabel)
                                    .addComponent(alamatLabel))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(namaField, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                                    .addComponent(jenis_kelaminCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(noTelpLabel3)
                                    .addComponent(noTelpLabel2)
                                    .addComponent(noTelpLabel)
                                    .addComponent(noTelpLabel1))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(b_Simpan)
                                        .addGap(18, 18, 18)
                                        .addComponent(b_Keluar))
                                    .addComponent(tempat_lahirField)
                                    .addComponent(tanggal_lahirField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(alamatField, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idDonaturLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alamatLabel)
                    .addComponent(jenis_kelaminCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noTelpLabel)
                    .addComponent(tempat_lahirField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noTelpLabel1)
                    .addComponent(tanggal_lahirField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noTelpLabel2)
                    .addComponent(alamatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b_Simpan)
                        .addComponent(b_Keluar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(noTelpLabel3)
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaFieldKeyTyped
        char c = evt.getKeyChar();
        if(!((Character.isLetter(c)
            || (c == KeyEvent.VK_BACK_SPACE)
            || (c == KeyEvent.VK_DELETE)
            || (c == KeyEvent.VK_SPACE)
            || (c == KeyEvent.VK_ENTER)))) {
    getToolkit().beep();
    JOptionPane.showMessageDialog(null, "Masukkan Huruf A-Z");
    evt.consume();
    }
    if (c == evt.VK_ENTER) {
        tempat_lahirField.requestFocus();
        }   // TODO add your handling code here:
    }//GEN-LAST:event_namaFieldKeyTyped

    private void b_KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_KeluarActionPerformed
        // memanggil method keluar
        //selesaikan dulu prosedur method keluar
        //kemudian tambahkan pemanggilan method tersebut
        keluar();
    }//GEN-LAST:event_b_KeluarActionPerformed

    private void b_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_SimpanActionPerformed
        // memanggil method simpan
        //selesaikan dulu prosedur method simpan
        //kemudian tambahkan pemanggilan method tersebut
        simpan();
    }//GEN-LAST:event_b_SimpanActionPerformed

    private void jenis_kelaminComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenis_kelaminComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenis_kelaminComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(_Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(_Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(_Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(_Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                _Entry dialog = new _Entry(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatField;
    private javax.swing.JLabel alamatLabel;
    public javax.swing.JButton b_Keluar;
    public javax.swing.JButton b_Simpan;
    private javax.swing.JLabel idDonaturLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jenis_kelaminCombo;
    private javax.swing.JTextField namaField;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JLabel noTelpLabel;
    private javax.swing.JLabel noTelpLabel1;
    private javax.swing.JLabel noTelpLabel2;
    private javax.swing.JLabel noTelpLabel3;
    private javax.swing.JTextField passwordField;
    private javax.swing.JFormattedTextField tanggal_lahirField;
    private javax.swing.JTextField tempat_lahirField;
    private javax.swing.JTextField user_idField;
    // End of variables declaration//GEN-END:variables

private boolean append;
    String Vuser_id, Vnama, Vjenis_kelamin, Vtempat_lahir, Vtanggal_lahir, Valamat, Vpassword;
    String _temp_user;
    String _Status;
    String _User;
    //membuat deklarasi variabel
    mstr_user PD = new mstr_user();
    //membuat objek baru PD mewarisi class mstr_user
    
    //tambahan method
    public _Entry() {
    }
    
    void autono() {
        try {
            Connection _Cnn = logic_koneksi.getConnection();
            String sql = "select max(right(user_id,2)) AS idAuto from mstr_user";
            Statement st = _Cnn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                if (rs.first() == false) {
                    user_idField.setText("User-01");
                } else {
                    rs.last();
                    int auto_f = rs.getInt(1) + 1;
                    String no = String.valueOf(auto_f);
                    int NoLong = no.length();
                    //jumlah 0
                    for (int a = 0; a < 2 - NoLong; a++) {
                        no = "0" + no;
                    }
                    user_idField.setText("User-" + no);
                }
            }
            rs.close();
            st.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR: \n" + e.toString(), "Kesalahan", JOptionPane.WARNING_MESSAGE);
        }
    }
    
     void clearfield() {
        user_idField.setEditable(false);
        namaField.setEditable(false);
        jenis_kelaminCombo.setSelectedItem(0);
        tempat_lahirField.setEditable(false);
        tanggal_lahirField.setEditable(false);
        alamatField.setEditable(false);
        passwordField.setEditable(false);
        b_Simpan.setVisible(append);
    }
     
     private boolean ValidasiInput() {
        boolean result = false;
        JOptionPane pane = new JOptionPane();
        
        if (user_idField.getText().equals("")
                || namaField.getText().equals("")
                || jenis_kelaminCombo.getSelectedItem().equals("Pilih Jenis Kelamin")
                || tempat_lahirField.getText().equals("")
                || tanggal_lahirField.getText().equals("")
                || alamatField.getText().equals("")
                || passwordField.getText().equals("")){
            JDialog dialog = pane.createDialog(null,"Lengkapi Record Data");
            dialog.setAlwaysOnTop(true);
            dialog.setVisible(true);
            //JOptionPane.showMessageDialog(this, "Atribut tidak valid", "Informasi", 0);
            if ((user_idField.getText().equals(""))) {
                user_idField.requestFocus();
                String user_id = JOptionPane.showInputDialog("User ID?");
                user_idField.setText(user_id);
            }
            if ((namaField.getText().equals(""))) {
                namaField.requestFocus();
                String nama = JOptionPane.showInputDialog("Nama User?");
                namaField.setText(nama);
            }
            if ((jenis_kelaminCombo.getSelectedItem().equals("Pilih Jenis Kelamin"))) {
                jenis_kelaminCombo.requestFocus(); 
                String JKPane[] = {"Pilih Jenis Kelamin","Laki-laki","Perempuan"};
                JComboBox cb = new JComboBox(JKPane);
                int jenis_kelamin;
                jenis_kelamin = JOptionPane.showConfirmDialog(this,cb,"Jenis Kelamin User?",
                        JOptionPane.DEFAULT_OPTION);
                if(jenis_kelamin == JOptionPane.OK_OPTION) {
                    String pilihJK = (String)cb.getSelectedItem();
                    jenis_kelaminCombo.setSelectedItem(pilihJK);
                }
            }
            if ((tempat_lahirField.getText().equals(""))) {
                tempat_lahirField.requestFocus();
                String tempat_lahir = JOptionPane.showInputDialog("Tempat Lahir User?");
                tempat_lahirField.setText(tempat_lahir);
            }
            if ((tanggal_lahirField.getText().equals(""))) {
                tanggal_lahirField.requestFocus();
                String tanggal_lahir = JOptionPane.showInputDialog("Tanggal Lahir User? \nContoh Format : 2001-8-21(yyyy-M-d)");
                tanggal_lahirField.setText(tanggal_lahir);
            }
            if ((alamatField.getText().equals(""))) {
                alamatField.requestFocus();
                String alamat = JOptionPane.showInputDialog("Alamat User?");
                alamatField.setText(alamat);
            }
            if ((passwordField.getText().equals(""))) {
                passwordField.requestFocus();
                String password = JOptionPane.showInputDialog("Password User?");
                passwordField.setText(password);
            }
            result = false;
        } else {
            result = true;
        }
        return result;
    }
     
    void simpan() {
        if (ValidasiInput() == false) {
            return;
        } else {
            try {
                PD.Cari(user_idField.getText());
                PD.user_id = user_idField.getText();
                PD.nama = namaField.getText();
                PD.jenis_kelamin = jenis_kelaminCombo.getSelectedItem().toString();
                PD.tempat_lahir = tempat_lahirField.getText();
                PD.tanggal_lahir = tanggal_lahirField.getText();
                PD.alamat = alamatField.getText();
                PD.password = passwordField.getText();
                if (PD._Akses.equals("-")) {
                    user_idField.setEditable(false);
                    int pilih = JOptionPane.showConfirmDialog(this, "Record data : \n"
                            + user_idField.getText() + "\n"
                            + namaField.getText() + "\n"
                            + jenis_kelaminCombo.getSelectedItem()+ "\n"
                            + tempat_lahirField.getText() + "\n"
                            + tanggal_lahirField.getText() + "\n"
                            + alamatField.getText() + "\n"
                            + passwordField.getText() + "\n"
                            + "Akan terupdate ??", "NOTIFIKASI UPDATE RECORD", JOptionPane.YES_OPTION);
                    if (pilih == JOptionPane.YES_OPTION) {
                        PD.updatedata();
                        clearfield();
                    }
                } else {
                    user_idField.setEditable(false);
                    int pilih = JOptionPane.showConfirmDialog(this, "Record data : \n"
                            + user_idField.getText() + "\n"
                            + namaField.getText() + "\n"
                            + jenis_kelaminCombo.getSelectedItem()+ "\n"
                            + tempat_lahirField.getText() + "\n"
                            + tanggal_lahirField.getText() + "\n"
                            + alamatField.getText() + "\n"
                            + passwordField.getText() + "\n"
                            + "Akan ditambahkan ke database USER??", "NOTIFIKASI SIMPAN RECORD", JOptionPane.YES_OPTION);
                    if(pilih == JOptionPane.YES_OPTION) {
                        PD.simpandata();
                        clearfield();
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Kesalahan " + e);
            }
        }
    }
    
    void keluar() {
        append = false;
        this.setVisible(append);
    }
    
    private void cari() {
        try {
            PD.Cari(_temp_user);
            if (PD._Akses.equals("-")) {
                user_idField.setText(PD.user_id);
                namaField.setText(PD.nama);
                jenis_kelaminCombo.setSelectedItem(PD.jenis_kelamin);
                tempat_lahirField.setText(PD.tempat_lahir);
                tanggal_lahirField.setText(PD.tanggal_lahir);
                alamatField.setText(PD.alamat);
                passwordField.setText(PD.password);
                user_idField.setEditable(false);
            }
        } catch (Exception e) {
            
        }
    }
    
    public _Entry(String user, String V_user_id, String status) {
        initComponents();
        autono();
        _temp_user = V_user_id;
        if (status.equals("Edit")) {
            System.out.println("kode dipilih " + V_user_id);
            b_Simpan.setText("Update");
        }
        _Status = status;
        _User = user;
        cari();
    }
}
