/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ControlRoom;

/**
 *
 * @author Glora
 */

import Class.logic_koneksi;
import java.awt.*;
import java.io.IOException;
import java.sql.SQLException;
import javax.swing.*;
import report.FrmLaporanUser;
import report.Frmpengunjung;
import report.FrmLaporan;

public class frmMenuUtama extends javax.swing.JFrame {
    
    private boolean append;
    Dimension parentSize = this.getSize();

    
    public frmMenuUtama() {
        initComponents();
        settingkoneksi();
        Dimension DMax = Toolkit.getDefaultToolkit().getScreenSize();
        this.setMaximumSize(DMax);
        this.setExtendedState (JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Login = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        Logout = new javax.swing.JMenuItem();
        Keluar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        ldp = new javax.swing.JMenu();
        l_d_u = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));

        jDesktopPane1.setForeground(new java.awt.Color(255, 153, 204));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        Login.setText("Switch User");

        jMenuItem1.setText("Login");
        Login.add(jMenuItem1);

        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        Login.add(Logout);

        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        Login.add(Keluar);

        jMenuBar1.add(Login);

        jMenu2.setText("Master");

        jMenuItem4.setText("List Pengunjung");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("List Penjualan");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("List Admin/Kasir");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        ldp.setText("Laporan");

        l_d_u.setText("Laporan Data User");
        l_d_u.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_d_uActionPerformed(evt);
            }
        });
        ldp.add(l_d_u);

        jMenuItem9.setText("Laporan pengunjung");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        ldp.add(jMenuItem9);

        jMenuBar1.add(ldp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        menuUser();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        append = false;
        this.setVisible(append);
        new frmLogin().setVisible(true);
        
    }//GEN-LAST:event_LogoutActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_KeluarActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
       menuPenjualan();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        menuProduk();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void l_d_uActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_d_uActionPerformed
        // TODO add your handling code here:
        FrmLaporanUser l = new FrmLaporanUser();
        jDesktopPane1.add(l);
        parentSize = this.getSize();
        Dimension childSize = l.getSize();
        l.setLocation((parentSize.width = childSize.width)/2 ,(parentSize.height = childSize.height)/ 2);
        l.setVisible(true);
        l.btampil.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    l.btampil.setText("Cetak Data User");
                }
        });
    }//GEN-LAST:event_l_d_uActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        Frmpengunjung l = new Frmpengunjung();
        jDesktopPane1.add(l);
        parentSize = this.getSize();
        Dimension childSize = l.getSize();
        l.setLocation((parentSize.width = childSize.width)/2 ,(parentSize.height = childSize.height)/ 2);
        l.setVisible(true);
        l.btampil.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    l.btampil.setText("Cetak Data pengunjung");
                }
        });
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Keluar;
    private javax.swing.JMenu Login;
    private javax.swing.JMenuItem Logout;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem l_d_u;
    private javax.swing.JMenu ldp;
    // End of variables declaration//GEN-END:variables
private void settingkoneksi() {
        logic_koneksi setting = new logic_koneksi();
        setting.makeConnect();
        if (setting.isConnected() == true) {
            JOptionPane.showMessageDialog(null, "Terhubung dengan Database");
        
        } else {
            JOptionPane.showMessageDialog(null, "Koneksi database gagal");
        }
    }
    
    private void menuProduk(){
        Mstr_Produk._List Dn = new Mstr_Produk._List();
        Dn = new Mstr_Produk._List();
        jDesktopPane1.add(Dn);
        parentSize = this.getSize();
        Dimension childSize = Dn.getSize();
        Dn.setLocation((parentSize.width = childSize.width)/2 ,(parentSize.height = childSize.height)/ 2);
        Dn.setVisible(true);
        
    }
    
    private void menuPenjualan(){
        Mstr_penjualan._List ftp = new Mstr_penjualan._List();
        ftp = new Mstr_penjualan._List();
        jDesktopPane1.add(ftp);
        parentSize = this.getSize();
        Dimension childSize = ftp.getSize();
        ftp.setLocation((parentSize.width = childSize.width)/2 ,(parentSize.height = childSize.height)/ 2);
        ftp.setVisible(true);
        
   }

    private void menuUser() {
        Mstr_User._List Dn = new Mstr_User._List();
        Dn = new Mstr_User._List();
        jDesktopPane1.add(Dn);
        parentSize = this.getSize();
        Dimension childSize = Dn.getSize();
        Dn.setLocation((parentSize.width = childSize.width)/2 ,(parentSize.height = childSize.height)/ 2);
        Dn.setVisible(true);
    }
}
